[package]
name = "token-generator"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "http://github.com/CodeChain-io/rust-token-generator"

[dependencies]
limited-table = "0.1.0"
